# Generated by Django 5.2.15 on 2026-06-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Hero Name (English)')),
                ('name_vn', models.CharField(max_length=100, verbose_name='Hero Name (Vietnamese)')),
                ('name_ppl', models.CharField(max_length=100, verbose_name='Hero Name (Popular)')),
                ('name_url', models.URLField(verbose_name='Hero Image URL (if needed)')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.IntegerField(verbose_name='Home Team Score')),
                ('away_team_score', models.IntegerField(verbose_name='Away Team Score')),
                ('stage', models.CharField(max_length=100, verbose_name='Match Stage (e.g. Group Stage, Quarterfinals)')),
                ('date', models.DateField(verbose_name='Game Date')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('logo_url', models.URLField(verbose_name='Team Logo URL (if needed)')),
                ('region', models.CharField(max_length=100, verbose_name='Team Region')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tournament Name')),
                ('game_version', models.CharField(choices=[('VGVD', 'Chinese Mainland Version'), ('HOK', 'Global Version'), ('AOV', 'Arna of Valor Version')], max_length=10, verbose_name='Game Version')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField(verbose_name='Game Number (e.g. Game 1, Game 2)')),
                ('duration', models.CharField(max_length=20, verbose_name='Game Duration')),
                ('winner_side', models.CharField(choices=[('BLUE', 'Blue side'), ('RED', 'Red side')], max_length=10, verbose_name='Winning Side')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='db.match')),
                ('blue_side_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_side_games', to='db.team')),
                ('red_side_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_side_games', to='db.team')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Player Name')),
                ('ign', models.CharField(max_length=100, verbose_name='In-Game Name')),
                ('default_role', models.CharField(max_length=100, verbose_name='Default Role')),
                ('signature_hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_players', to='db.hero')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='db.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='db.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='db.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='db.tournament'),
        ),
        migrations.CreateModel(
            name='GameLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(choices=[('CLASH', 'Clash lane'), ('JUNGLE', 'Jungle'), ('MID', 'Mid lane'), ('FARM', 'Farm lane'), ('ROAM', 'Roaming')], max_length=10, verbose_name='Lane')),
                ('kills', models.IntegerField(default=0, verbose_name='Kills')),
                ('deaths', models.IntegerField(default=0, verbose_name='Deaths')),
                ('assists', models.IntegerField(default=0, verbose_name='Assists')),
                ('gold', models.IntegerField(default=0, verbose_name='Gold')),
                ('is_mvp', models.BooleanField(default=False, verbose_name='Is MVP')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='db.game', verbose_name='Game')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='db.hero', verbose_name='Hero')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='db.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Game Lineup',
                'verbose_name_plural': 'Game Lineups',
                'unique_together': {('game', 'hero'), ('game', 'player')},
            },
        ),
        migrations.CreateModel(
            name='GameDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(verbose_name='Draft Slot (1-20)')),
                ('action_type', models.CharField(choices=[('BAN', 'Ban'), ('PICK', 'Pick')], max_length=10, verbose_name='Action Type')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='db.game', verbose_name='Game')),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='db.hero', verbose_name='Hero')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='db.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Game Draft',
                'verbose_name_plural': 'Game Drafts',
                'ordering': ['slot'],
                'unique_together': {('game', 'slot')},
            },
        ),
    ]
