# Generated by Django 5.2.15 on 2026-06-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_game_mvp_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelineup',
            name='is_mvp',
        ),
    ]
