# Generated by Django 5.2.15 on 2026-06-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_gamelineup_is_mvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelineup',
            name='gold',
        ),
    ]
